-- Minimal local prerequisites, not a deployable schema or a copy of staging.
-- Baseline uploaded_files/profile DDL is not fully versioned in this repository.
-- The test loads real MAIN table DDL, auth helpers, triggers and RPC bodies separately.
create role authenticated nologin nobypassrls;
create role anon nologin nobypassrls;
create schema auth;
create table auth.users (id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$$;
grant usage on schema public, auth to authenticated, anon;
grant execute on function auth.uid() to authenticated, anon;

-- Nullable/invalid profile fixtures deliberately exercise fail-closed policy behavior.
create table public.profiles (id uuid primary key, workspace text, role text);
create table public.employees (
  id uuid primary key, workspace text, hr_scope text, full_name text,
  attendance_name text, employment_status text default 'active',
  is_deleted boolean default false, start_date date
);
create table public.uploaded_files (
  id uuid primary key default gen_random_uuid(), workspace text not null,
  file_name text not null, uploaded_at timestamptz default now(),
  is_deleted boolean default false, deleted_at timestamptz, deleted_by uuid,
  deleted_batch_id uuid, deleted_reason text, removed_from_recycle_bin boolean default false
);
create table public.late_records (
  id bigint generated by default as identity primary key,
  workspace text, employee_name text, work_date date, time_in time,
  minutes_late integer, seconds_late integer, total_seconds_late integer,
  minutes_undertime integer, source_file_id text, source_file_name text,
  is_deleted boolean default false, deleted_at timestamptz, deleted_by uuid,
  deleted_batch_id uuid, deleted_reason text, removed_from_recycle_bin boolean default false
);
create table public.generated_undertimes (like public.late_records including all);
create table public.absences (
  id uuid primary key default gen_random_uuid(), workspace text, employee_id uuid,
  employee_name text, work_date date, reason text, informed_to text[], source_type text,
  source_attendance_date date, source_file_id uuid,
  is_deleted boolean default false, deleted_at timestamptz, deleted_by uuid,
  deleted_batch_id uuid, deleted_reason text, removed_from_recycle_bin boolean default false
);
create table public.half_day_records (
  id uuid primary key default gen_random_uuid(), workspace text, employee_id uuid,
  employee_name text, work_date date, absent_period text, scheduled_start time,
  scheduled_end time, reason text, created_by uuid, source_type text,
  source_file_name text, source_file_id uuid, source_time_in time,
  restored_at timestamptz, restored_by uuid,
  is_deleted boolean default false, deleted_at timestamptz, deleted_by uuid,
  deleted_batch_id uuid, deleted_reason text, removed_from_recycle_bin boolean default false,
  unique(employee_id,work_date,absent_period)
);
create table public.exemptions (late_record_id bigint);
