-- Forward-only production preparation. NOT APPLIED.
begin;
do $$ declare c record; begin
 for c in select conname from pg_constraint where conrelid='public.exemptions'::regclass and contype='c' and pg_get_constraintdef(oid) ilike '%approval_status%' loop execute format('alter table public.exemptions drop constraint %I',c.conname); end loop;
 update public.exemptions set approval_status='declined' where approval_status='rejected';
 alter table public.exemptions add constraint exemptions_approval_status_check check (approval_status in ('pending', 'approved', 'declined'));
end $$;
alter table public.exemptions add column if not exists late_restored_at timestamptz, add column if not exists late_restored_by uuid references auth.users(id);
alter table public.half_day_records add column if not exists employee_name text, add column if not exists is_deleted boolean not null default false, add column if not exists deleted_at timestamptz, add column if not exists deleted_by uuid references auth.users(id), add column if not exists deleted_reason text, add column if not exists deleted_batch_id uuid, add column if not exists restored_at timestamptz, add column if not exists restored_by uuid references auth.users(id), add column if not exists removed_from_recycle_bin boolean not null default false, add column if not exists removed_from_recycle_bin_at timestamptz, add column if not exists removed_from_recycle_bin_by uuid references auth.users(id);
update public.half_day_records h set employee_name=e.full_name from public.employees e where h.employee_id=e.id and h.employee_name is null;
alter table public.half_day_records alter column employee_name set not null;
create or replace function public.restore_exemption_late(p_id bigint) returns void language plpgsql security definer set search_path='' as $$ declare x public.exemptions%rowtype; begin if auth.uid() is null or public.attendance_role()<>'HR' then raise exception 'Only HR can restore linked late records'; end if; select * into x from public.exemptions where id=p_id and not is_deleted for update; if x.id is null or x.approval_status<>'approved' or x.late_record_id is null then raise exception 'Approved linked exemption required'; end if; if x.late_restored_at is not null then raise exception 'Linked late record is already restored'; end if; update public.exemptions set late_restored_at=now(),late_restored_by=auth.uid() where id=p_id; end $$;
create or replace function public.create_half_day(p_employee_id uuid,p_date date,p_period text,p_reason text) returns uuid language plpgsql security definer set search_path='' as $$ declare e public.employees%rowtype; s time; f time; new_id uuid; dow int; begin if auth.uid() is null or public.attendance_role()<>'HR' then raise exception 'Only HR can create half-day records'; end if; select * into e from public.employees where id=p_employee_id and not is_deleted and employment_status='active'; if e.id is null then raise exception 'Active employee required'; end if; dow=extract(dow from p_date); if dow=0 then raise exception 'Sunday has no half-day schedule'; end if; if dow=6 then if p_period='morning' then s='07:00';f='11:00'; elsif p_period='afternoon' then s='11:00';f='15:15'; else raise exception 'Invalid period'; end if; else if p_period='morning' then s='08:00';f='12:00'; elsif p_period='afternoon' then s='13:00';f='17:00'; else raise exception 'Invalid period'; end if; end if; insert into public.half_day_records(workspace,employee_id,employee_name,work_date,absent_period,scheduled_start,scheduled_end,reason,created_by) values(e.workspace,e.id,e.full_name,p_date,p_period,s,f,nullif(btrim(p_reason),''),auth.uid()) returning id into new_id; return new_id; end $$;
create or replace function public.delete_half_day(p_id uuid) returns void language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null or public.attendance_role()<>'HR' then raise exception 'Only HR can delete half-day records'; end if; update public.half_day_records set is_deleted=true,deleted_at=now(),deleted_by=auth.uid(),deleted_reason='half_day_deleted',deleted_batch_id=gen_random_uuid(),restored_at=null,restored_by=null,removed_from_recycle_bin=false,removed_from_recycle_bin_at=null,removed_from_recycle_bin_by=null where id=p_id and not is_deleted; if not found then raise exception 'Active half-day record not found'; end if; end $$;
create or replace function public.create_generated_half_day(p_workspace text,p_employee_name text,p_date date,p_period text,p_reason text,p_source_file_name text default null) returns uuid language plpgsql security definer set search_path='' as $$ declare e public.employees%rowtype; s time; f time; new_id uuid; begin if auth.uid() is null or public.attendance_role()<>'HR' then raise exception 'Only HR can generate half-day records'; end if; if p_period<>'afternoon' then raise exception 'Generated attendance supports afternoon half-day only'; end if; select * into e from public.employees where workspace=p_workspace and not is_deleted and employment_status='active' and public.employee_name_key(full_name)=public.employee_name_key(p_employee_name); if e.id is null then raise exception 'Active employee required'; end if; if extract(dow from p_date)=6 then s='11:00';f='15:15'; else s='13:00';f='17:00'; end if; update public.generated_undertimes set is_deleted=true,deleted_at=now(),deleted_reason='reclassified_as_half_day' where workspace=p_workspace and work_date=p_date and not is_deleted and public.employee_name_key(employee_name)=public.employee_name_key(e.full_name); insert into public.half_day_records(workspace,employee_id,employee_name,work_date,absent_period,scheduled_start,scheduled_end,reason,created_by,source_type,source_file_name) values(e.workspace,e.id,e.full_name,p_date,'afternoon',s,f,nullif(btrim(p_reason),''),auth.uid(),'attendance_upload',nullif(btrim(p_source_file_name),'')) on conflict (employee_id,work_date,absent_period) do update set scheduled_start=excluded.scheduled_start,scheduled_end=excluded.scheduled_end,reason=excluded.reason,source_type=excluded.source_type,source_file_name=excluded.source_file_name,is_deleted=false,restored_at=now(),restored_by=auth.uid(),removed_from_recycle_bin=false returning id into new_id; return new_id; end $$;
create or replace function public.restore_half_day(p_id uuid) returns void language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null or public.attendance_role()<>'HR' then raise exception 'Only HR can restore half-day records'; end if; update public.half_day_records set is_deleted=false,restored_at=now(),restored_by=auth.uid(),removed_from_recycle_bin=false,removed_from_recycle_bin_at=null,removed_from_recycle_bin_by=null where id=p_id and is_deleted; if not found then raise exception 'Deleted half-day record not found'; end if; end $$;
create or replace function public.hide_half_day_from_recycle_bin(p_id uuid) returns void language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null or public.attendance_role()<>'HR' then raise exception 'Only HR can manage half-day records'; end if; update public.half_day_records set removed_from_recycle_bin=true,removed_from_recycle_bin_at=now(),removed_from_recycle_bin_by=auth.uid() where id=p_id and is_deleted and not removed_from_recycle_bin; if not found then raise exception 'Deleted half-day record not found'; end if; end $$;
revoke all on function public.restore_exemption_late(bigint),public.delete_half_day(uuid),public.restore_half_day(uuid),public.hide_half_day_from_recycle_bin(uuid),public.create_half_day(uuid,date,text,text),public.create_generated_half_day(text,text,date,text,text,text) from public,anon;
grant execute on function public.restore_exemption_late(bigint),public.delete_half_day(uuid),public.restore_half_day(uuid),public.hide_half_day_from_recycle_bin(uuid),public.create_half_day(uuid,date,text,text),public.create_generated_half_day(text,text,date,text,text,text) to authenticated;
commit;

